---
title: "CountyAgCommData"
author: "RPrice"
date: "2/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Creating 1 file with all years of County Ag Commissioner's Data

##Creating a list of files to read in
### (Note that the complete errata is used for 2018)
```{r}
cac0 <- list.files(path = "~/2_School/3_Internship/Models/CountyAgCommData/", full.names = FALSE)
cac0 #list of all files in the folder
```

```{r}
a <- c(41:42) #identifying files to remove
cac <- cac0[-a] #remove unwanted files
cac #list of desired files
```

##Reading in the data
```{r}
cac_list <- list(NA)
for (i in 1:length(cac)) {
  cac_list[[i]] <- read.csv(cac[i])
}
View(cac_list) #40 dataframes in list
```

##Prepare to merge dataframes
###Confirm columns match/are mergable
```{r}
for (i in 2:length(cac_list)) { #confirm column names match
  f <- colnames(cac_list[[1]]) == colnames(cac_list[[i]])
  print(f)
} #one does not match
```
```{r}
i<-23
colnames(cac_list[[1]]) == colnames(cac_list[[i]]) #23 does not match
```
```{r}
colnames(cac_list[[1]]) #examine standard names
```

```{r}
colnames(cac_list[[23]]) #columns are the same, can just change names
```

```{r}
colnames(cac_list[[23]]) <- colnames(cac_list[[1]]) #change col names
colnames(cac_list[[23]]) 
```

##Merge all years
```{r}
cac_all <- data.frame(cac_list[[1]])
for (i in 2:length(cac_list)) {
  cac_all <- rbind(cac_all,data.frame(cac_list[[i]]))
}
cac_all
```
##Save merged data
```{r}
#setwd("~/2_School/3_Internship/Models/CountyAgCommData") #to desktop
#write.csv(cac_all,file = "CountyAgComm_All.csv",row.names = FALSE)
```
